### PR TITLE
template changes for select dropdowns

### PR DESCRIPTION
**Pull request by donjo**
styles in eregs/regulations-site#345

### CODE REVIEW

**Comment by cmc333333** [comment]
:+1:

**Comment by cmc333333** [comment]
Curious: do you think the associated styles are particular to notice-and-comment (and hence belong in this repo rather than -site?)

**Comment by donjo** [comment]
Possible. In theory I would imagine other comment periods would use a similar format, in which case they would probably want to copy the structure of this file. Right now though the `comment-additional-info.html` in site is just blank so it exists to be over-written. Maybe we should create a stripped down version to put in -site so people know what the structure (and classes) should look like?

**Comment by cmc333333** [comment]
Agreed at the challenge of documenting these features. I think it's safe to say we'll be the only group that'll add something similar in the near future, however, so probably not worth losing sleep on it just yet. Maybe just referencing this template will do for now.

**Pull request merged**
