### PR TITLE
Initial OpenControl Docs

### PR DESCRIPTION
**Pull request by cmc333333**
Initial documentation for our controls -- used in the ATO.

### CODE REVIEW

**Comment by afeld** [comment]
Looks great so far! Have you been able to [generate the docs](https://github.com/opencontrol/compliance-masonry#creating-gitbook-documentation) successfully? Does [gap analysis](https://github.com/opencontrol/compliance-masonry#gap-analysis) give you information that makes sense?

**Comment by cmc333333** [comment]
@afeld re gap analysis -- I don't see any different in the list (25 missing controls) after adding AC-2. Do I need a "implementation_status"? If so, what is there a set of values I should be using?

**Comment by afeld** [comment]
> I don't see any difference in the list (25 missing controls) after adding AC-2. Do I need a "implementation_status"?

Not sure...is the problem described in https://github.com/opencontrol/schemas/issues/24?

> what is there a set of values I should be using?

https://github.com/opencontrol/schemas/blob/8256be311d83aab73d4bfd0cc855f79b33359ae5/opencontrol-component-kwalify-schema.yaml#L78-L84

**Comment by cmc333333** [comment]
@afeld Thanks! I'll keep plugging away

**Pull request merged**
