### PR TITLE
Fix read/write tab colors

### PR DESCRIPTION
**Pull request by xtine**
Make sure Read and Write tab colors are correct, per #256

screen shot 2016-05-09 at 12 50 02 pm

When hovering over Write tab:
screen shot 2016-05-09 at 12 55 31 pm

### CODE REVIEW

**Comment by donjo** [comment]
I think maybe we should do a `lighten(10%, @grey)` (or whatever the variable is for the navbar) for the background color when hovering over the non-active tab. Taking white out makes sense but I think it should have a little bit of a button effect.

**Comment by donjo** [comment]
Another thing that changed at some point (which is probably what made that link blue in the first place) is causing the icon of the active tab to be too close to the text. The text for the active tab should get a `padding: 0 5px` which used to be applied by a `.preamble-header > span` that still applies to the inactive tab but not the active one.

**Comment by xtine** [comment]
So there was a few padding changes due to the fact that mobile hides the "the proposal" and "a comment" text. I've added left padding to the active mode link to account for that.

**Comment by xtine** [comment]
@donjo: I added the lighten gray hover on the non-active tab and the hover gives a nice pop effect. Good suggestion:

screen shot 2016-05-10 at 11 03 51 am

**Comment by donjo** [comment]
Looks good 👍

**Comment by cmc333333** [comment]
Two thumbs!

**Pull request merged**
