### PR TITLE
new table of contents style 

### PR DESCRIPTION
**Pull request by donjo**
screen shot 2016-04-05 at 4 27 54 pm

This covers the new tab style for notice-and-comment table of contents which replaces the table of contents icon with an abbreviation and adds a subheader below the words Table of Contents to further explain the contents of the tab the user is looking at.

### CODE REVIEW

**Comment by cmc333333** [comment]
Is there anything in `notice_and_comment/templates/regulations/preamble-chrome.html` that shouldn't belong in -site?

**Comment by xtine** [comment]
If we're overriding the entire `preamble-chrome.html`, does it still make sense to break out the header in `preamble-header.html` in -site? Because then we could just remove header from -site so we have one less file to manage.

**Comment by cmc333333** [comment]
I'd like to steer us away from overriding the whole file, if possible. We can use blocks, `overextends`, and subtemplates to replace just the components we need.

**Comment by donjo** [comment]
yep I'm happy to restructure this in a way that it just replaces a specific block. As of right now this is the only part that changed

```django
{% block sidebar-icons %}
<li>
  <a href="#table-of-contents" id="menu-link" class="toc-nav-link current" title="Preamble Table of Contents">
    <span class="menu-tab">Pre</span>
  </a>
</li>
{% endblock %}
```

**Pull request merged**
